
# █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀
# ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█


# Example windowrule v1
# windowrule = float, ^(kitty)$
# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

windowrule = opacity 0.90 0.90,match:class firefox
windowrule = opacity 0.90 0.90,match:class Brave-browser
windowrule = opacity 0.80 0.80,match:class Steam
windowrule = opacity 0.80 0.80,match:class steam
windowrule = opacity 0.80 0.80,match:class steamwebhelper
windowrule = opacity 0.80 0.80,match:class Spotify
windowrule = opacity 0.80 0.80,match:class Code
windowrule = opacity 0.80 0.80,match:class code-url-handler
windowrule = opacity 0.80 0.80,match:class kitty
windowrule = opacity 0.80 0.80,match:class foot
windowrule = opacity 0.80 0.80,match:class org.kde.dolphin
windowrule = opacity 0.80 0.80,match:class org.kde.ark
windowrule = opacity 0.80 0.80,match:class nwg-look
windowrule = opacity 0.80 0.80,match:class qt5ct

windowrule = opacity 0.90 0.90,match:class com.github.rafostar.Clapper
windowrule = opacity 0.80 0.80,match:class com.github.tchx84.Flatseal
windowrule = opacity 0.80 0.80,match:class hu.kramo.Cartridges
windowrule = opacity 0.80 0.80,match:class com.obsproject.Studio
windowrule = opacity 0.80 0.80,match:class gnome-boxes
windowrule = opacity 0.80 0.80,match:class discord
windowrule = opacity 0.80 0.80,match:class WebCord
windowrule = opacity 0.80 0.80,match:class app.drey.Warp
windowrule = opacity 0.80 0.80,match:class net.davidotek.pupgui2
windowrule = opacity 0.80 0.80,match:class yad
windowrule = opacity 0.80 0.80,match:class Signal
windowrule = opacity 0.80 0.80,match:class io.gitlab.theevilskeleton.Upscaler

windowrule = opacity 0.80 0.70,match:class pavucontrol
windowrule = opacity 0.80 0.70,match:class blueman-manager
windowrule = opacity 0.80 0.70,match:class nm-applet
windowrule = opacity 0.80 0.70,match:class nm-connection-editor
windowrule = opacity 0.80 0.70,match:class org.kde.polkit-kde-authentication-agent-1

windowrule = float 1,match:class qt5ct
windowrule = float 1,match:class nwg-look
windowrule = float 1,match:class org.kde.ark
windowrule = float 1,match:class Signal
windowrule = float 1,match:class com.github.rafostar.Clapper
windowrule = float 1,match:class app.drey.Warp
windowrule = float 1,match:class net.davidotek.pupgui2
windowrule = float 1,match:class yad
windowrule = float 1,match:class eog
windowrule = float 1,match:class io.gitlab.theevilskeleton.Upscaler
windowrule = float 1,match:class pavucontrol
windowrule = float 1,match:class blueman-manager
windowrule = float 1,match:class nm-applet
windowrule = float 1,match:class nm-connection-editor
windowrule = float 1,match:class org.kde.polkit-kde-authentication-agent-1

